#region Consulta nbs_clientes
query_nbs_clientes = """

SELECT        
    'NBS' AS SISTEMAORIGEM,
    T1.COD_CLIENTE AS CODCLIENTE,
    T1.NOME AS CLIENTE,
    CASE T3.TIPO_END WHEN '1' THEN 'OUTRO' WHEN '2' THEN 'RESIDENCIAL' WHEN '3' THEN 'COMERCIAL' WHEN '4' THEN 'COBRANÇA' ELSE 'OUTRO' END AS TIPOENDERECO,
    T3.PRINCIPAL AS ENDERECOPRINCIPAL,
    T3.UF AS UF,
    T4.DESCRICAO AS CIDADE,
    --T3.COD_CIDADE,      
    T3.BAIRRO AS BAIRRO,
    T3.LOGRADOURO AS LOGRADOURO,
    T3.NUM AS NUMERO,
    T3.COMPL AS COMPLEMENTO,
    T3.CEP AS CEP,
    T1.ENDERECO_ELETRONICO AS EMAIL,
    CONCAT(T1.PREFIXO_RES, T1.TELEFONE_RES) AS TELL,
    CONCAT(T1.PREFIXO_CEL, T1.TELEFONE_CEL) AS CELL,
    CASE WHEN T1.COD_CLASSE = 'F' THEN 'FISICA'
         WHEN T1.COD_CLASSE = 'J' THEN 'JURIDICA'
        ELSE '****' 
    END AS TIPOFJ,
    CASE
		WHEN T1.COD_CLASSE = 'F' THEN LPAD(T1.cod_cliente, 11, '0')
		WHEN T1.COD_CLASSE = 'J' THEN LPAD(T1.cod_cliente, 14, '0')
	END AS DOCCLI,
    TO_CHAR(T2.DATA_CADASTRO, 'YYYY-MM-DD HH24:MI:SS') AS DATA_CADASTRO,
    TO_CHAR(T2.DATA_ULTIMA_ATUALIZACAO, 'YYYY-MM-DD HH24:MI:SS') AS DATA_ULTIMA_ATUALIZACAO
FROM CLIENTES T1
LEFT JOIN CLIENTE_DIVERSO T2 ON T2.COD_CLIENTE  = T1.COD_CLIENTE 
LEFT JOIN VW_ENDERECO T3 ON T3.COD_CLIENTE  = T1.COD_CLIENTE
LEFT JOIN CIDADES T4 ON T4.COD_CIDADES = T3.COD_CIDADE 
WHERE 
    EXISTS (SELECT DISTINCT COD_CLIENTE FROM VENDAS WHERE COD_CLIENTE = T1.COD_CLIENTE)
    """
#endregion

#region Consulta nbs_financeiro
query_nbs_financeiro = """

SELECT 
  T1.agente_cobrador
, T1.cliente
, T1.cod_cliente
, T1.cod_empresa
, T1.cod_vendedor
, TO_CHAR(T1.data_cancelamento, 'YYYY-MM-DD')      	AS data_cancelamento
, TO_CHAR(T1.Data_Contemplacao, 'YYYY-MM-DD')      	AS Data_Contemplacao    
, TO_CHAR(T1.data_emissao, 'YYYY-MM-DD')            	AS data_emissao         
, TO_CHAR(T1.Data_Entrega_Bem, 'YYYY-MM-DD')        	AS Data_Entrega_Bem     
, TO_CHAR(T1.data_pagamento, 'YYYY-MM-DD')      	       AS data_pagamento      
, TO_CHAR(T1.data_previsao_pagamento, 'YYYY-MM-DD')     AS data_previsao_pagamento 
, TO_CHAR(T1.data_vencimento, 'YYYY-MM-DD')         	AS data_vencimento       
, T1.departamento
, T1.doccli
, T1.eh_devolucao
, T1.empresa
, T1.forma_pagamento
, T1.juros
, T1.lancamento_financeiro
, T1.matriz
, T1.multa
, T1.natureza_operacao
, T1.negativado
, T1.NOSSO_NUMERO
, T1.nota_fiscal_codigo
, T1.nota_fiscal_numero
, T1.nota_fiscal_serie
, T1.num_titulo
, T1.parcela
, T1.situacao_cobranca
, T1.Situacao_cota
, T1.status_titulo
, T1.sistemaorigem
, T1.tem_devolucao
, T1.tipo_movimento
, T1.tipo_titulo
, T1.tipo_recurso
, T1.tipo_formapagto
, T1.titulo_saldo
, T1.valor_comissao
, T1.valor_devido
, T1.valor_fundo_reserva
, T1.valor_nominal_titulo
, T1.valor_seguro
, T1.valor_taxa_adminstrativa
, NULL AS valor_titulo
, T1.valorpago
, T1.vendedor
, T1.cd_grupo
, T1.grupo
, T1.cd_cota
, T1.versao
, T1.Plano_Venda
, T1.Ponto_Venda

FROM
(
        -- CONTAS A RECEBER CARTÃO DE CREDITO
        SELECT 
            'NBS' AS SISTEMAORIGEM, 
            'N' AS TEM_DEVOLUCAO,
            'N' AS EH_DEVOLUCAO,
            C.COD_CLIENTE AS COD_CLIENTE,
            C.NOME AS CLIENTE,    
            CASE WHEN CD.CPF IS NULL THEN CD.CGC
                 WHEN CD.CGC IS NULL THEN CD.CPF 
                 END AS DOCCLI,    
            CAST(E.COD_EMPRESA AS VARCHAR(10)) AS COD_EMPRESA,
            CAST(E.NOME AS VARCHAR(150)) AS EMPRESA,
            (SELECT NOME FROM EMPRESAS WHERE COD_EMPRESA = E.COD_MATRIZ) AS MATRIZ, 
            'A RECEBER' as TIPO_MOVIMENTO,  
            CC.NOME AS TIPO_TITULO,
            'CARTAO DE CREDITO' AS FORMA_PAGAMENTO,
	     'Próprio' AS TIPO_RECURSO,
	     'A prazo' AS TIPO_FORMAPAGTO,
            
            CASE WHEN CP.DATA_BAIXA IS NOT NULL 
                THEN 'QUITADO' 
                ELSE CASE WHEN CP.DATA_VENCIMENTO >= SYSDATE THEN 'A VENCER' ELSE 'VENCIDO' END 
            END AS STATUS_TITULO,            
          
            'ATIVO' AS DESC_STATUS,
            NULL AS AGENTE_COBRADOR,
            NAT.DESCRICAO AS NATUREZA_OPERACAO, 
            DEP.DESCRICAO AS DEPARTAMENTO,
            RPAD('0',9-LENGTH(CAST(cr.COD_CONTROLE_CARTAO AS VARCHAR(9))),'0') || CAST(cr.COD_CONTROLE_CARTAO AS VARCHAR(9)) || RPAD('0',2-LENGTH(CAST(CP.PARCELA AS VARCHAR(2))),'0') || CAST(CP.PARCELA AS VARCHAR(2)) AS LANCAMENTO_FINANCEIRO,
            NULL AS NOSSO_NUMERO,   
            CR.COD_CONTROLE_CARTAO AS NUM_TITULO,
            CP.PARCELA AS PARCELA,
            CP.VALOR AS VALORPAGO,          
            (CP.VALOR - CP.VALOR_DESPESA) AS VALOR_DEVIDO,            
            NULL AS SITUACAO_COBRANCA,
            NULL AS SITUACAO_COTA,          
            NULL AS NEGATIVADO,
            NULL AS DATA_CANCELAMENTO,
            CR.DATA AS DATA_EMISSAO,
            CP.DATA_VENCIMENTO AS DATA_VENCIMENTO,
            CP.DATA_VENCIMENTO AS DATA_PREVISAO_PAGAMENTO,
            CP.DATA_BAIXA AS DATA_PAGAMENTO,
            CP.VALOR AS VALOR_TITULO,                   
            CP.VALOR AS TITULO_SALDO,
            Cc.Comissao_Cartao AS VALOR_COMISSAO,                                                       --- ????????
            GETVENDEDORCARTAO (CR.COD_EMPRESA, CR.COD_CONTROLE_CARTAO) AS COD_VENDEDOR, 
            (SELECT NOME_COMPLETO FROM EMPRESAS_USUARIOS WHERE NOME = GETVENDEDORCARTAO (CR.COD_EMPRESA, CR.COD_CONTROLE_CARTAO)) AS VENDEDOR,
            VD.CONTROLE AS NOTA_FISCAL_CODIGO,              
            NULL AS NOTA_FISCAL_NUMERO,
            VD.SERIE AS NOTA_FISCAL_SERIE,  
            NULL AS valor_fundo_reserva,
            NULL AS valor_nominal_titulo,
            NULL AS valor_seguro,
            NULL AS valor_taxa_adminstrativa,           
            NULL AS MULTA,
            NULL AS JUROS,          
            NULL AS CD_GRUPO,
            NULL AS GRUPO, 
            NULL AS CD_COTA,
            NULL AS VERSAO,
            NULL AS PLANO_VENDA,
            NULL AS PONTO_VENDA,
            NULL AS DATA_CONTEMPLACAO,
            NULL AS DATA_ENTREGA_BEM
        
        FROM CRECEBER_CARTAO CR
        
        INNER JOIN CRECEBER_CARTAO_PARC CP 
        ON 
        CR.COD_EMPRESA = CP.COD_EMPRESA AND CR.COD_CONTROLE_CARTAO = CP.COD_CONTROLE_CARTAO AND CR.DATA = CP.DATA
        
        INNER JOIN CARTAO_CREDITO CC 
        ON
        CC.COD_EMPRESA = CR.COD_EMPRESA AND CC.COD_CARTAO_CREDITO = CR.COD_CARTAO_CREDITO
        
        INNER JOIN CLIENTES C  
        ON
        C.COD_CLIENTE = CR.COD_CLIENTE 
        
        INNER JOIN CLIENTE_DIVERSO CD 
        ON
        CR.COD_CLIENTE = CD.COD_CLIENTE 
        
        INNER JOIN EMPRESAS E
        ON
        E.COD_EMPRESA = CR.COD_EMPRESA
        
        LEFT JOIN VENDAS VD
        ON
        VD.COD_EMPRESA = CR.COD_EMPRESA AND VD.CONTROLE = CR.CONTROLE_VENDA AND VD.SERIE = CR.SERIE_VENDA
        
        LEFT JOIN CONTA_CORRENTE CT
        ON 
        CT.COD_EMPRESA = CP.COD_EMPRESA AND CT.COD_CONTA_CORRENTE = CP.CONTA_BAIXA
        
        LEFT JOIN NATUREZA_RECEITA_DESPESA NAT
        ON 
        NAT.COD_NATUREZA_RECEITA_DESPESA  = CR.COD_NATUREZA_RECEITA_DESPESA AND NAT.COD_GRUPO_PC = CR.COD_GRUPO_PC

        LEFT JOIN EMPRESAS_DEPARTAMENTOS DEP
        ON
        DEP.COD_EMPRESA_DEPARTAMENTO = VD.COD_EMPRESA_DEPARTAMENTO AND DEP.COD_EMPRESA = VD.COD_EMPRESA
        
        WHERE 
        --CP.DATA_VENCIMENTO >= TO_DATE((SELECT ADD_MONTHS(SYSDATE, -12*5) FROM DUAL)) AND 
        E.COD_EMPRESA NOT IN (200, 301, 302)   

        UNION ALL   
              
        -- CONTA A RECEBER - SIMPLES
        SELECT DISTINCT
            'NBS' as SISTEMAORIGEM, 
            NVL(FR.TEM_DEVOLUCAO,'N') AS TEM_DEVOLUCAO,
            NVL(FR.EH_DEVOLUCAO,'N') AS EH_DEVOLUCAO,
          C.COD_CLIENTE AS COD_CLIENTE,
            C.NOME AS CLIENTE,    
            CASE WHEN CD.CPF IS NULL THEN CD.CGC
                 WHEN CD.CGC IS NULL THEN CD.CPF 
                 END AS DOCCLI,    
            CAST(E.COD_EMPRESA AS VARCHAR(10)) AS COD_EMPRESA,
            CAST(E.NOME AS VARCHAR(150)) AS EMPRESA,
            (SELECT NOME FROM EMPRESAS WHERE COD_EMPRESA = E.COD_MATRIZ) AS MATRIZ, 
            'A RECEBER' as TIPO_MOVIMENTO,  
            FP.DESCRICAO AS TIPO_TITULO,
            fc.DESCRICAO  AS FORMA_PAGAMENTO,
	     CASE WHEN FC.COD_FORMA_COBRANCA IN (10,15,16,56)
		THEN 'Banco'
		ELSE 'Próprio'
	     END AS TIPO_RECURSO,

	     CASE WHEN FC.COD_FORMA_COBRANCA IN (3,29,31,127)
		THEN 'A prazo'
		ELSE 'À vista' 
	     END AS TIPO_FORMAPAGTO,
            
            CASE WHEN CR.DATA_BAIXA IS NOT NULL 
                THEN 'QUITADO' 
                ELSE CASE WHEN (CR.SALDO_PARCELA > 0 AND (CR.SALDO_PARCELA < CR.VALOR_PARCELA))
                          THEN 'QUITADO PARCIALMENTE' 
                          ELSE CASE WHEN CR.DATA_VENCIMENTO >= SYSDATE THEN 'A VENCER' ELSE 'VENCIDO' END 
                     END
            END AS STATUS_TITULO,                                   

            SF.DESCRICAO AS DESC_STATUS,
            NULL AS AGENTE_COBRADOR,
            nrd.DESCRICAO AS NATUREZA_OPERACAO, 
            DEP.DESCRICAO AS DEPARTAMENTO,
            RPAD('0',9-LENGTH(CAST(cr.NR_FATURA AS VARCHAR(9))),'0') || CAST(cr.NR_FATURA AS VARCHAR(9)) || RPAD('0',2-LENGTH(CAST(cr.PARCELA AS VARCHAR(2))),'0') || CAST(cr.PARCELA AS VARCHAR(2)) AS LANCAMENTO_FINANCEIRO,
            TO_CHAR(NVL(CR.NOSSO_NUMERO,'')) || '-' ||  NVL(CR.DG_NOSSO_NUMERO,'') AS NOSSO_NUMERO, 
            CR.NR_FATURA AS NUM_TITULO,
            CR.PARCELA AS PARCELA,
            
            (SELECT SUM(VALOR_PRINCIPAL) 
                FROM BAIXA_CONTAS_RECEBER 
                WHERE COD_EMPRESA = CR.COD_EMPRESA 
                    AND NR_FATURA = CR.NR_FATURA 
                    AND PARCELA = CR.PARCELA 
                    AND COD_TIPO_FATURA = CR.COD_TIPO_FATURA 
                    AND DATA_EMISSAO = CR.DATA_EMISSAO) AS VALOR_PAGO,       
                    
            CR.SALDO_PARCELA AS VALOR_DEVIDO,               
            
            NULL AS SITUACAO_COBRANCA,
            NULL AS SITUACAO_COTA,
            NVL(CR.NEGATIVADO,'N') as NEGATIVADO,
            FR.DATA_CANCEL AS DATA_CANCELAMENTO,
            CR.DATA_EMISSAO AS DATA_EMISSAO,
            CR.DATA_VENCIMENTO AS DATA_VENCIMENTO,
            CR.DATA_VENCIMENTO AS DATA_PREVISAO_PAGAMENTO,
            CR.DATA_BAIXA AS DATA_PAGAMENTO,
            CR.VALOR_PARCELA AS VALOR_TITULO,

            --V.TOTAL_NOTA, 
            CR.SALDO_PARCELA AS TITULO_SALDO,
            CR.VALOR_COMISSAO  AS VALOR_COMISSAO,
            EU.NOME AS COD_VENDEDOR,
            EU.NOME_COMPLETO AS VENDEDOR,
            cr.NR_FATURA AS NOTA_FISCAL_CODIGO,
            
            GETNUMERONF(CR.COD_EMPRESA, CR.COD_TIPO_FATURA, CR.NR_FATURA, CR.DATA_EMISSAO, 'S') || ' - '  || GETNUMERONF(CR.COD_EMPRESA, CR.COD_TIPO_FATURA, CR.NR_FATURA, CR.DATA_EMISSAO,'N','S') AS NOTA_FISCAL_NUMERO,
                         
            NULL AS NOTA_FISCAL_SERIE,              
            NULL AS valor_fundo_reserva,
            NULL AS valor_nominal_titulo,
            NULL AS valor_seguro,
            NULL AS valor_taxa_adminstrativa,           
            NULL AS MULTA,
            NULL AS JUROS,          
            NULL AS CD_GRUPO,
            NULL AS GRUPO, 
            NULL AS CD_COTA,
            NULL AS VERSAO,
            NULL AS PLANO_VENDA,
            NULL AS PONTO_VENDA,    
            NULL AS DATA_CONTEMPLACAO,
            NULL AS DATA_ENTREGA_BEM
            
        FROM CONTAS_RECEBER CR 
        
        INNER JOIN FATURA_RECEBER FR  
        ON 
        CR.NR_FATURA = FR.NR_FATURA AND CR.COD_EMPRESA = FR.COD_EMPRESA AND CR.COD_TIPO_FATURA = FR.COD_TIPO_FATURA AND CR.DATA_EMISSAO = FR.DATA_EMISSAO 
        
        LEFT JOIN VW_FATURA_RECEBER_DETALHE FRD 
        ON 
        frd.COD_EMPRESA = CR.COD_EMPRESA AND frd.NR_FATURA = fr.NR_FATURA AND FRD.COD_TIPO_FATURA = FR.COD_TIPO_FATURA AND FR.DATA_EMISSAO = CR.DATA_EMISSAO 
        
        INNER JOIN CLIENTES C 
        ON 
        C.COD_CLIENTE = FR.COD_CLIENTE 
        
        LEFT JOIN FORMA_COBRANCA FC 
        ON 
        CR.COD_EMPRESA_FC = FC.COD_EMPRESA AND CR.COD_FORMA_COBRANCA = FC.COD_FORMA_COBRANCA
        
        LEFT JOIN GRUPO_FORMA_COBRANCA GF 
        ON 
        FC.COD_MATRIZ  = GF.COD_MATRIZ AND FC.COD_GR_FORMA_COBRANCA = GF.COD_GR_FORMA_COBRANCA
        
        LEFT JOIN CLIENTE_DIVERSO CD 
        ON 
        CD.COD_CLIENTE = C.COD_CLIENTE
        
        LEFT JOIN EMPRESAS E 
        ON 
        E.COD_EMPRESA = FR.COD_EMPRESA      
        
        LEFT JOIN FORMA_PGTO FP 
        ON 
        FP.COD_EMPRESA = CR.COD_EMPRESA AND FP.COD_FORMA_PGTO = CR.COD_FORMA_PGTO 

        LEFT JOIN EMPRESAS_DEPARTAMENTOS DEP
        ON
        DEP.COD_EMPRESA_DEPARTAMENTO = FP.COD_EMPRESA_DEPARTAMENTO AND DEP.COD_EMPRESA = FC.COD_EMPRESA

        LEFT JOIN FORMA_COBRANCA FC 
        ON 
        FC.COD_EMPRESA = CR.COD_EMPRESA AND FC.COD_FORMA_COBRANCA = CR.COD_FORMA_PGTO
        
        LEFT JOIN NATUREZA_RECEITA_DESPESA NRD
        ON 
        NRD.COD_NATUREZA_RECEITA_DESPESA  = FR.COD_NATUREZA_RECEITA_DESPESA  AND NRD.COD_GRUPO_PC = FR.COD_GRUPO_PC 
        
        LEFT JOIN EMPRESAS_USUARIOS EU 
        ON 
        EU.NOME = FR.USUARIO AND EU.COD_EMPRESA = FR.COD_EMPRESA 
        
        LEFT JOIN STATUS_FINANCEIRO SF
        ON 
        FR.COD_STATUS = SF.COD_STATUS
        
        WHERE   FR.COD_STATUS = 0
                AND CR.TIPO_CARTEIRA = 0 
                AND CR.COD_EMPRESA NOT IN (200, 301, 302)                      
          
) T1
"""
#endregion

#region Consulta nbs_faturamento
query_nbs_faturamento = """

SELECT 
  'NBS' AS SISTEMAORIGEM,
    C.COD_CLIENTE AS CODCLIENTE,
    C.NOME AS CLIENTE,    
    CASE
		WHEN C.COD_CLASSE = 'F' THEN LPAD(c.cod_cliente, 11, '0')
		WHEN C.COD_CLASSE = 'J' THEN LPAD(c.cod_cliente, 14, '0')
	END AS DOCCLI, 
	RPAD('0',3-LENGTH(CAST(V.COD_EMPRESA AS VARCHAR(3))),'0') || CAST(V.COD_EMPRESA AS VARCHAR(3)) || RPAD('0',9-LENGTH(CAST(V.CONTROLE AS VARCHAR(9))),'0') || CAST(V.CONTROLE AS VARCHAR(9)) || V.SERIE AS CHAVE_FATURAMENTO,   
  TO_CHAR(V.EMISSAO, 'YYYY-MM-DD') AS DATA_NF,    
    VI.CONTROLE,
    CAST(VI.SERIE AS VARCHAR(10)) AS SERIE,
  OP.COD_NATUREZA_RECEITA_DESPESA,
  CAST(V.STATUS AS VARCHAR(30)) AS STATUS,    
    VI.COD_FORNECEDOR,
    CAST(VI.COD_CENTRO_CUSTO AS VARCHAR(30)) AS COD_CENTRO_CUSTO,
  CAST(E.COD_EMPRESA AS VARCHAR(10)) AS COD_EMPRESA,
  CAST(E.NOME AS VARCHAR(150)) AS EMPRESA,
  G.COD_GRUPO_PC,
    G.DESCRICAO AS GRUPO_PC,     
  CAST(I.COD_ITEM AS VARCHAR(30)) AS COD_ITEM,  
    I.DESCRICAO AS ITEM,  
    'N' AS NOVO_USADO,    
    I.COD_GRUPO_INTERNO,
    I.COD_SUB_GRUPO_INTERNO,    
    VI.COD_NATUREZA,   
    VI.COD_OPERACAO_FISCAL,
    VI.DESCONTO_RATEADO,
    VI.DIAS_GIRO,
    VI.GRUPO,
  CC.CUSTO_RESULTANTE, -- CUSTO_OP OU CUSTO_RESUL SEMELHANTES = CUSTO PROD    
    VI.QTDE AS QUANT,
    VI.QTDE_DEVOLVIDA AS QUANT_DEV,
  CC.CUSTO_OPERACAO AS CUSTO_PRODUTO, -- CUSTO_OP OU CUSTO_RESUL SEMELHANTES = CUSTO PROD
    VI.PRECO_UNITARIO AS PUNIT, -- USE AQUI 
  (VI.TOTAL_DESCONTOS / VI.QTDE) AS DESC_PUNIT,    
  (VI.PRECO_UNITARIO - (VI.TOTAL_DESCONTOS / VI.QTDE)) AS PVENDIDO,
  ((VI.PRECO_UNITARIO - (VI.TOTAL_DESCONTOS / VI.QTDE)) / CC.CUSTO_OPERACAO) AS MARGEM,
  V.TOTAL_NOTA, 
  ((VI.PRECO_UNITARIO - (VI.TOTAL_DESCONTOS / VI.QTDE)) * VI.QTDE) AS TOTAL_VENDA_SDEV,
  ((VI.QTDE_DEVOLVIDA * (VI.PRECO_UNITARIO - (VI.TOTAL_DESCONTOS / VI.QTDE)))*-1) + ((VI.PRECO_UNITARIO - (VI.TOTAL_DESCONTOS / VI.QTDE)) * VI.QTDE) AS TOTAL_VENDA_CDEV,
  ((VI.QTDE_DEVOLVIDA) * (VI.PRECO_UNITARIO)) AS TOTAL_DEVOLVIDO,
  VI.TOTAL_DESCONTOS AS DESC_TOTAL, -- USE AQUI -- OBS ESSE DESC É GERAL, P/ REALIZAR DESC_UNIT DIVIDA POR QUANT TOTAL DE ITENS
  OS.NUMERO_OS,
  OST.TIPO AS COD_TIPO_OS,
  OST.DESCRICAO AS TIPO_OS,
  OST.INTERNO,
    OST.GERA_FINANCEIRO,
    V.COD_MODELO,                      
    V.COD_OPERACAO,
    V.COD_SETOR,
    V.COD_EMPRESA_DIVISAO,
  EU.NOME AS COD_VENDEDOR,
    EU.NOME_COMPLETO AS VENDEDOR,    
    V.COD_EMPRESA_DEPARTAMENTO,   
    'PEÇAS' AS TABREF

FROM VENDAS V

INNER JOIN CLIENTES C ON C.COD_CLIENTE = V.COD_CLIENTE

LEFT JOIN PAGAMENTO_VENDA PV ON PV.CONTROLE = V.CONTROLE AND PV.SERIE = V.SERIE  AND PV.COD_EMPRESA = V.COD_EMPRESA

INNER JOIN VENDA_ITENS VI ON VI.COD_EMPRESA = V.COD_EMPRESA AND VI.CONTROLE = V.CONTROLE AND VI.SERIE = V.SERIE

LEFT JOIN ITENS I ON I.COD_ITEM = VI.COD_ITEM 

INNER JOIN OPERACOES OP ON OP.COD_EMPRESA = V.COD_EMPRESA AND OP.COD_OPERACAO = V.COD_OPERACAO

LEFT JOIN GRUPO_PC G ON G.COD_GRUPO_PC = VI.COD_GRUPO_PC

LEFT JOIN EMPRESAS E ON E.COD_EMPRESA = V.COD_EMPRESA

LEFT JOIN EMPRESAS_USUARIOS EU ON EU.NOME = V.VENDEDOR

LEFT JOIN OS ON OS.COD_EMPRESA = V.COD_EMPRESA AND OS.NUMERO_OS = V.NUMERO_OS

LEFT JOIN OS_TIPOS OST ON OST.TIPO = OS.TIPO 

LEFT JOIN CARDEX_CONTABIL CC ON CC.COD_EMPRESA = V.COD_EMPRESA AND CC.CONTROLE = V.CONTROLE AND CC.COD_ITEM = VI.COD_ITEM

LEFT JOIN CLIENTE_DIVERSO CD ON CD.COD_CLIENTE = C.COD_CLIENTE

LEFT JOIN CIDADES CI ON CI.COD_CIDADES= CD.COD_CIDADES

WHERE
--WHERE V.VENDEDOR <> 'NBS' --NBS É ADM DO SISTEMA E DEVE SER RETIRADO PARA EVITAR DUPLICIDADES
V.COD_OPERACAO IN (1, 2, 3, 13, 19, 22, 26)
--v.emissao BETWEEN ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12) AND TRUNC(SYSDATE, 'DD')
AND NVL(V.STATUS,'') <> 1

UNION ALL

SELECT 
  'NBS' AS SYSORIGEM,
  C.COD_CLIENTE,
  C.NOME AS CLIENTE,  
  CASE
		WHEN C.COD_CLASSE = 'F' THEN LPAD(c.cod_cliente, 11, '0')
		WHEN C.COD_CLASSE = 'J' THEN LPAD(c.cod_cliente, 14, '0')
	END AS DOCCLI,
	RPAD('0',3-LENGTH(CAST(V.COD_EMPRESA AS VARCHAR(3))),'0') || CAST(V.COD_EMPRESA AS VARCHAR(3)) || RPAD('0',9-LENGTH(CAST(V.CONTROLE AS VARCHAR(9))),'0') || CAST(V.CONTROLE AS VARCHAR(9)) || V.SERIE AS CHAVE_FATURAMENTO,
TO_CHAR(VP.DATA_VENDA, 'YYYY-MM-DD') AS DATA_NF,    
  NVL(VP.CONTROLE_NOTA_INTERNET,V.CONTROLE) AS CONTROLE,
    CAST(V.SERIE AS VARCHAR(10)) AS SERIE,  
  NULL AS COD_NATUREZA_RECEITA_DESPESA,
    CAST(VP.STATUS_PROPOSTA AS VARCHAR(30)) AS STATUS,  
    NULL AS COD_FORNECEDOR, 
    NULL AS  COD_CENTRO_CUSTO,    
  CAST(E.COD_EMPRESA AS VARCHAR(10)) AS COD_EMPRESA,
  CAST(E.NOME AS VARCHAR(150)) AS EMPRESA,    
  NULL AS COD_GRUPO_PC,
  NULL AS GRUPO_PC,     
  CAST(VE.COD_PRODUTO AS VARCHAR(30)) AS COD_ITEM,  
    P.DESCRICAO_PRODUTO AS ITEM,
    VE.NOVO_USADO,
    NULL AS COD_GRUPO_INTERNO,
    NULL AS COD_SUB_GRUPO_INTERNO,    
    V.COD_NATUREZA AS COD_NATUREZA,   
    NULL AS COD_OPERACAO_FISCAL,
    NULL AS DESCONTO_RATEADO,
    0 AS DIAS_GIRO,
    NVL(V.GRUPO,VP.GRUPO) AS GRUPO,
  VE.CUSTO_TOTAL_FINAL AS CUSTO_RESULTANTE, -- CUSTO_OP OU CUSTO_RESUL SEMELHANTES = CUSTO PROD    
    1 AS QUANT,
    0 AS QUANT_DEV,
  VE.CUSTO_TOTAL_FINAL AS CUSTO_PRODUTO, -- CUSTO_OP OU CUSTO_RESUL SEMELHANTES = CUSTO PROD
  VP.VALOR_PROPOSTA AS PUNIT, -- USE AQUI
  (VP.DESCONTO + VP.DESCONTO_OUTROS) AS DESC_PUNIT,
  VP.VALOR_PROPOSTA AS PVENDIDO,
  VE.MARGEM_FINAL AS MARGEM,
  VP.VALOR_PROPOSTA AS TOTAL_NOTA,
  VP.VALOR_PROPOSTA AS TOTAL_VENDA_SDEV,
  0 AS TOTAL_VENDA_CDEV,  
  0 AS TOTAL_DEVOLVIDO,
  VP.DESCONTO AS DESC_TOTAL,
  V.NUMERO_OS AS NUMERO_OS,
  NULL AS COD_TIPO_OS,
  NULL AS TIPO_OS,
  NULL AS INTERNO,
  NULL AS GERA_FINANCEIRO,
    VE.COD_MODELO,                      
    V.COD_OPERACAO AS COD_OPERACAO,
    V.COD_SETOR AS COD_SETOR, 
    NULL AS COD_EMPRESA_DIVISAO,
  EU.NOME AS COD_VENDEDOR,
    EU.NOME_COMPLETO AS VENDEDOR,    
    V.COD_EMPRESA_DEPARTAMENTO AS COD_EMPRESA_DEPARTAMENTO,   
    'VEICULOS' AS TABREF   

FROM VEICULOS_PROPOSTAS VP  

INNER JOIN CLIENTES C ON C.COD_CLIENTE = VP.COD_CLIENTE

LEFT JOIN VENDAS V ON V.COD_PROPOSTA = VP.COD_PROPOSTA AND V.COD_EMPRESA = VP.COD_EMPRESA AND V.STATUS = 0

LEFT JOIN PAGAMENTO_VENDA PV ON PV.CONTROLE = V.CONTROLE AND PV.SERIE = V.SERIE  AND PV.COD_EMPRESA = V.COD_EMPRESA

LEFT JOIN CLIENTE_DIVERSO CD ON CD.COD_CLIENTE = C.COD_CLIENTE

LEFT JOIN VENDAS V ON V.COD_PROPOSTA = VP.COD_PROPOSTA AND V.COD_EMPRESA = VP.COD_EMPRESA AND V.STATUS = 0

LEFT JOIN EMPRESAS E ON E.COD_EMPRESA = VP.COD_EMPRESA_VENDA

LEFT JOIN VEICULOS VE  ON VE.COD_PRODUTO = VP.COD_PRODUTO AND VE.COD_CLIENTE= VP.COD_CLIENTE AND VE.CHASSI_RESUMIDO = VP.CHASSI_RESUMIDO

LEFT JOIN PRODUTOS P ON P.COD_PRODUTO  = VE.COD_PRODUTO

LEFT JOIN EMPRESAS_USUARIOS EU ON EU.NOME = VP.VENDEDOR

WHERE 
--VP.DATA_VENDA BETWEEN ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12) AND TRUNC(SYSDATE, 'DD') AND
VP.STATUS_PROPOSTA = 'V'

UNION ALL 

SELECT  
  'NBS' AS SYSORIGEM,
    C.COD_CLIENTE AS CODCLIENTE,
    C.NOME AS CLIENTE,    
    CASE
		WHEN C.COD_CLASSE = 'F' THEN LPAD(c.cod_cliente, 11, '0')
		WHEN C.COD_CLASSE = 'J' THEN LPAD(c.cod_cliente, 14, '0')
	END AS DOCCLI, 
	RPAD('0',3-LENGTH(CAST(V.COD_EMPRESA AS VARCHAR(3))),'0') || CAST(V.COD_EMPRESA AS VARCHAR(3)) || RPAD('0',9-LENGTH(CAST(V.CONTROLE AS VARCHAR(9))),'0') || CAST(V.CONTROLE AS VARCHAR(9)) || V.SERIE AS CHAVE_FATURAMENTO,   
  TO_CHAR(os.DATA_EMISSAO, 'YYYY-MM-DD') AS DATA_NF,    
  V.CONTROLE,
    CAST(V.SERIE AS VARCHAR(10)) AS SERIE,
  OP.COD_NATUREZA_RECEITA_DESPESA,
    CAST(OS.STATUS_OS AS VARCHAR(30)) AS STATUS,  
    NULL AS COD_FORNECEDOR,  
    CAST(CC.COD_CENTRO_CUSTO AS VARCHAR(30)) AS COD_CENTRO_CUSTO,    
  CAST(OS.COD_EMPRESA AS VARCHAR(10)) AS COD_EMPRESA ,
  CAST(E.NOME AS VARCHAR(150)) AS EMPRESA,  
  OS.COD_GRUPO_PC AS COD_GRUPO_PC,
    G.DESCRICAO AS GRUPO_PC,      
  CAST(S.COD_SERVICO AS VARCHAR(30)) AS COD_ITEM,     
    S.DESCRICAO_SERVICO AS SERVICO, 
    'N' AS NOVO_USADO,
    NULL AS COD_GRUPO_INTERNO,
    NULL AS COD_SUB_GRUPO_INTERNO,      
    V.COD_NATUREZA,   
    NULL AS COD_OPERACAO_FISCAL, 
    OSR.DESCONTO_RATEADO, 
    0 AS DIAS_GIRO,
  CD.cliente_especial_grupo AS GRUPO,
  NULL AS CUSTO_RESULTANTE,
  1 AS QUANT,
    0 AS QUANT_DEV,
  S.PRECO_CUSTO AS CUSTO_PRODUTO, 
  OSR.PRECO_LIQUIDO_FINAL AS PUNIT,
    OSR.VALOR_DESCONTO_SERV AS DESC_UNIT,
    OSR.PRECO_VENDA AS PVENDIDO,
  NULL AS MARGEM,
  V.TOTAL_NOTA,
  NULL AS TOTAL_VENDA_SDEV,
    NULL AS TOTAL_VENDA_CDEV,
  NULL AS TOTAL_DEVOLVIDO,
  DECODE (OS.ORCAMENTO, 'S', ORC_ITEM_DESCONTO, DESCONTOS_ITENS) AS DESC_TOTAL, -- USE AQUI -- OBS ESSE DESC É GERAL, P/ REALIZAR DESC_UNIT DIVIDA POR QUANT TOTAL DE ITENS
  OS.NUMERO_OS,
  OST.TIPO AS COD_TIPO_OS,
  OST.DESCRICAO AS TIPO_OS,
  OST.INTERNO,
    OST.GERA_FINANCEIRO,
    V.COD_MODELO,                      
    V.COD_OPERACAO,
    V.COD_SETOR,
    V.COD_EMPRESA_DIVISAO,
  EU.NOME AS COD_VENDEDOR,
    EU.NOME_COMPLETO AS VENDEDOR,    
    V.COD_EMPRESA_DEPARTAMENTO,
    'SERVIÇOS' AS TABREF
FROM OS
INNER JOIN VENDAS V ON V.NUMERO_OS = OS.NUMERO_OS AND V.COD_EMPRESA  = OS.COD_EMPRESA AND V.COD_CLIENTE  = OS.COD_CLIENTE 
LEFT JOIN VENDA_OS VO ON V.CONTROLE = VO.CONTROLE AND V.COD_EMPRESA = VO.COD_EMPRESA AND V.SERIE  = VO.SERIE
LEFT JOIN PAGAMENTO_VENDA PV ON PV.CONTROLE = V.CONTROLE AND PV.SERIE = V.SERIE  AND PV.COD_EMPRESA = V.COD_EMPRESA
INNER JOIN OS_SERVICOS OSR ON OSR.NUMERO_OS = OS.NUMERO_OS
LEFT JOIN SERVICOS S ON S.COD_SERVICO = OSR.COD_SERVICO
INNER JOIN os_dados_veiculos DV ON DV.NUMERO_OS = OS.NUMERO_OS AND OS.COD_EMPRESA = DV.COD_EMPRESA
INNER JOIN CLIENTES C ON C.COD_CLIENTE = OS.COD_CLIENTE
LEFT JOIN CLIENTE_DIVERSO CD ON OS.COD_CLIENTE = CD.COD_CLIENTE
LEFT JOIN VW_LGPD_RE01 RE1 ON RE1.COD_CLIENTE =  CD.COD_CLIENTE
LEFT JOIN OPERACOES OP ON OP.COD_EMPRESA = V.COD_EMPRESA AND OP.COD_OPERACAO = V.COD_OPERACAO
LEFT JOIN produtos P ON  OS.COD_PRODUTO = P.COD_PRODUTO
LEFT JOIN GRUPO_PC G ON G.COD_GRUPO_PC = S.COD_GRUPO_SERV 
LEFT JOIN MARCAS M ON M.COD_MARCA = P.COD_MARCA
LEFT JOIN PRODUTOS_MODELOS PM ON PM.COD_MODELO = OS.COD_MODELO AND OS.COD_PRODUTO = PM.COD_PRODUTO
LEFT JOIN setor_venda SV ON SV.COD_SETOR = OS.COD_SETOR_VENDA 
LEFT JOIN os_status OSS ON OSS.STATUS_OS  = os.status_os
LEFT JOIN centro_custo CC ON CC.COD_CENTRO_CUSTO = os.cod_centro_custo AND CC.COD_GRUPO_PC = os.cod_grupo_pc
LEFT JOIN OS_Tipos OST ON OST.TIPO = OS.TIPO 
LEFT JOIN empresas_usuarios EU ON EU.nome = os.quem_abriu 
LEFT JOIN EMPRESAS E ON E.COD_EMPRESA = V.COD_EMPRESA

WHERE OS.ORCAMENTO = 'N'
    And Nvl(OS.Apagar_Ao_Sair, 'N') = 'N'
  And OS.STATUS_OS = 1
--  and (os.data_encerrada >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12))    and (os.data_encerrada < TRUNC(SYSDATE, 'MM'))
    and V.SERIE <> '1'
  and OST.INTERNO <> 'S'  
  and NVL(V.STATUS,'') <> 1

"""
#endregion

#region Deletes
deleteNbsClientes = """
	DELETE FROM staging.ext_clientes_nbs
"""

deleteNbsFinanceiro = """
	DELETE FROM staging.ext_financeiro_nbs
"""

deleteNbsFaturamento = """
	DELETE FROM staging.ext_faturamento_nbs
"""
#endregion